version: '3'
services:
  management:
    image: 'uazlibraries/ace-integrity-management:1.11'
    restart: always
    tty: true
    ports:
      - "8080:8080"
      - "8191:8181"
      - "4848:4848"
    environment:
      - DB_DATABASE=${ACE_IMS_DATABASE:-imsdb}
      - DB_HOST=${ACE_IMSDB_HOST:-db-host}
      - DB_PORT=${ACE_IMSDB_PORT:-3306}
      - DB_USER=${ACE_IMSDBA_USER:-aceims}
      - DB_PASSWORD=${ACE_IMSDBA_PASSWORD:-ace}
      - SMTP_HOST=${ACE_IMS_SMTP_HOST:-smtp.gmail.com:587}
      - SMTP_TLS=${ACE_IMS_SMTP_TLS:-true}
      - SMTP_USER=${ACE_IMS_SMTP_USER:-dockertestfilesender}
      - SMTP_PASSWORD=${ACE_IMS_SMTP_PASSWORD:-password=\"thisisalongpassword\"}
      - BOOTSTRAP_SLEEP=${ACE_IMS_BOOTSTRAP_SLEEP:-45}
