version: '3'
services:
  management:
    image: 'uazlibraries/ace-integrity-management:1.12'
    restart: always
    tty: true
    links:
      - db-host
    ports:
      - "8080:8080"
      - "8191:8181"
      - "4848:4848"
    environment:
      - DB_DATABASE=${ACE_IMS_DATABASE:-imsdb}
      - DB_HOST=${ACE_IMSDB_HOST:-db-host}
      - DB_PORT=${ACE_IMSDB_PORT:-3306}
      - DB_USER=${ACE_IMSDBA_USER:-aceims}
      - DB_PASSWORD=${ACE_IMSDBA_PASSWORD:-ace}
      - SMTP_HOST=${ACE_IMS_SMTP_HOST:-smtp.gmail.com:587}
      - SMTP_TLS=${ACE_IMS_SMTP_TLS:-true}
      - SMTP_USER=${ACE_IMS_SMTP_USER:-dockertestfilesender}
      - SMTP_PASSWORD=${ACE_IMS_SMTP_PASSWORD:-password=\"thisisalongpassword\"}
      - BOOTSTRAP_SLEEP=${ACE_IMS_BOOTSTRAP_SLEEP:-45}
    volumes:
      - run.mysql:/run/mysqld

  db-host:
    image: 'mysql:5.7'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ADMIN_PSWD:-insecure}
      - MYSQL_DATABASE=${ACE_IMS_DATABASE:-imsdb}
      - MYSQL_USER=${ACE_IMSDBA_USER:-aceims}
      - MYSQL_PASSWORD=${ACE_IMSDBA_PASSWORD:-ace}
      - MYSQL_ALLOW_EMPTY_PASSWORD='false'
    volumes:
      - ./mysql/large-index.cnf:/etc/mysql/mysql.conf.d/large-index.cnf
      - initdb.d:/docker-entrypoint-initdb.d
      - ${ACE_INTEGRITY_DBSTORE:-dbstore}:/var/lib/mysql
      - run.mysql:/run/mysqld

volumes:
  initdb.d:
  run.mysql:
  dbstore:
    
#    healthcheck:
#      test:  mysql --user=aceims --password=ace -e 'SELECT 1 FROM DUAL' aceimsdb
#      start_period: 10s
#      retries: 10
#    build: ./integrity
